Flights/urls.py
from django.urls import path
# from django.
from . import views

app_name = 'flights'

urlpatterns = [
    path( '', views.index, name='index' ),
    path( '/<int:flight_id>/', views.flight, name="flight" ),
    path( '/<int:flight_id>/book', views.book, name="book" ),
]

SAA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'flights', include('Flights.urls', namespace='flights') ),
    path( 'users', include( 'users.urls', namespace='users' ) ),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path( '', views.index, name='index' ),
    path( '/login', views.login_view, name='login' ),
    path( '/logout', views.logout_view, name='logout' ),
]

Flights/models.py
from django.db import models

# Create your models here.

class Airport(models.Model):

    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"


class Flight(models.Model):

    origin = models.ForeignKey( Airport, on_delete=models.CASCADE, related_name="departures" )
    destination = models.ForeignKey( Airport, on_delete=models.CASCADE, related_name="arrivals" )
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: from {self.origin} to {self.destination} for {self.duration} minutes"
    

class Passenger(models.Model):

    first = models.CharField( max_length=64 )
    last = models.CharField( max_length=64 )
    # The blank identifier helps us to allow users to have no flights assigned to them
    # The related_name identifier allows us to reverse access the users assigned to a certain flight
    flights = models.ManyToManyField( Flight, blank=True, related_name="passengers" )

    # For aesthetics
    def __str__(self) -> str:
        return f"{self.first} {self.last}"
    

users/models.py
from django.db import models

# Create your models here.

Flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Flight, Passenger


# Create your views here.

def index(request):
    return render( request, "Flights/index.html", {
        "flights": Flight.objects.all(),
    } )


def flight( request, flight_id ):
    """Gets the flight by flight ID"""
    print("This happpened")
    requested_flight = Flight.objects.get( pk=flight_id )
    passengers = requested_flight.passengers.all()
    return render( request, "Flights/flight.html", {
        "flight": requested_flight,
        "passengers": passengers,
        "non_passengers": Passenger.objects.exclude( flights=requested_flight ).all()
    } )


def book( request, flight_id ):

    if request.method == "POST":

        # Get the flight
        flight = Flight.objects.get( pk=flight_id )

        # Get the passenger by id
        passenger = Passenger.objects.get( pk = int(request.POST["passenger"]) )
        passenger.flights.add( flight )
        print("Right here")

        return HttpResponseRedirect( reverse( "flights:flight", args=(flight.id,) ) )

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# New guys say hi
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect( reverse("login") )
    return render( request, "users/index.html" )


def login_view( request ):
    if request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate( request, username=username, password=password )

        if not user:
            return render( request, "users/login.html", {
                "message": "invalid credentials"
            } )
        
        login( request, user )
        return HttpResponseRedirect( reverse( "users:index" ) )
    return render( request, "users/login.html" ) 


def logout_view( request ):
    logout( request )
    return render( request, "users/login.html", {
        "message": "Logged out",
    } )

Flights/templates/Flights/flight.html
{% extends 'Flights/layout.html' %}

{% block title %}

{{ flight.origin.code }} - {{ flight.destination.code }}

{% endblock %}
{% block body %}

<h2>
    Flight {{ flight.id }}
</h2>
<ul>
    <li> Origin : {{ flight.origin }} </li>
    <li> Destination : {{ flight.destination }} </li>
    <li> Duration : {{ flight.duration }} </li>
    <li> Destination : {{ flight.destination }} minutes </li>
</ul>

<h3>
    Passengers
</h3>
<ol>
    {% for passenger in passengers %}
    <li>{{ passenger.first }} {{ passenger.last }}</li>
    {% empty %}
    <li>No Passengers</li>
    {% endfor %}
</ol>

<h3>Add passenger</h3>

<form action="{% url 'flights:book' flight.id %}" method="post">
    {% csrf_token %}

    <!-- We want the user to select a passenger -->
     <select name="passenger">
        {% for passenger in non_passengers %}
            <option id="passenger-id" value="{{ passenger.id }}"> {{ passenger }} </option>
        {% endfor %}
     </select>

     <input type="submit">
</form>

<a href="{% url 'flights:index' %}">All Flights</a>

{% endblock %}

Flights/templates/Flights/index.html
{% extends 'Flights/layout.html' %}

{% block title %}
Home
{% endblock %}


{% block body %}

    <h1 id="headers-id"> All flights </h1>
    <ul>
        {% for flight in flights %}
        <li>
            <a href="{% url 'flights:flight' flight.id %}" id="flight-id">Flight {{ flight.id }}</a>
            : {{ flight.origin }} to {{ flight.destination }} for {{ flight.duration }} minutes
        </li>
        {% endfor %}
    </ul>

{% endblock %}

Flights/templates/Flights/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body id="main">
    {% block body %}
    {% endblock %}
</body>

</html>

users/templates/users/index.html
{% extends 'users/layout.html' %}

{% block title %}

{% endblock %}


{% block body %}

    <h1>
        Welcome, {{ request.user.first_name }}
    </h1>
    <ul>
        <li> Username: {{ request.user.username }} </li>
        <li> Email: {{ request.user.email }} </li>
    </ul>

    <a href="{% url 'users:logout' %}"> Log Out </a>

{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block title %}
{% endblock %}


{% block body %}

    {% if message %}
        <h4> {{ message }} </h4>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username:">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="Login">
    </form>
{% endblock %}